# Generated by Django 5.2.11 on 2026-02-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
